CREATE FUNCTION dbo.SplitInts (@list NVARCHAR(MAX))
RETURNS @Result TABLE
(
    Value INT NOT NULL
)
WITH SCHEMABINDING, EXECUTE AS OWNER
AS
BEGIN
    INSERT INTO @Result (Value)
    SELECT TRY_CONVERT(INT, value)
    FROM dbo.StringSplit(@list, ',');

    RETURN
END;

CREATE TABLE Employees (
    ID INT PRIMARY KEY,
    Name NVARCHAR(100),
    Salary DECIMAL(10, 2)
);

CREATE VIEW ActiveEmployees AS
SELECT * FROM Employees WHERE Salary > 0;

CREATE INDEX idx_EmpName ON Employees(Name);

CREATE USER MyUser FOR LOGIN MyLogin;

CREATE LOGIN MyLogin WITH PASSWORD = 'StrongPassword123';

CREATE FUNCTION GetSalary(@ID INT)
RETURNS DECIMAL(10, 2)
AS
BEGIN
    RETURN (SELECT Salary FROM Employees WHERE ID = @ID)
END;