DECLARE cur1 CURSOR
FOR SELECT * FROM dbo.TableA;

DECLARE cur1 INSENSITIVE SCROLL CURSOR
FOR SELECT * FROM dbo.TableA;

DECLARE cur1 CURSOR LOCAL
FOR SELECT * FROM dbo.TableA;

DECLARE cur2 CURSOR GLOBAL
FOR SELECT * FROM dbo.TableA;

DECLARE cur1 CURSOR FORWARD_ONLY
FOR SELECT * FROM dbo.TableA;

DECLARE cur2 CURSOR SCROLL
FOR SELECT * FROM dbo.TableA;

DECLARE cur1 CURSOR STATIC
FOR SELECT * FROM dbo.TableA;

DECLARE cur2 CURSOR KEYSET
FOR SELECT * FROM dbo.TableA;

DECLARE cur3 CURSOR DYNAMIC
FOR SELECT * FROM dbo.TableA;

DECLARE cur4 CURSOR FAST_FORWARD
FOR SELECT * FROM dbo.TableA;

DECLARE cur1 CURSOR READ_ONLY
FOR SELECT * FROM dbo.TableA;

DECLARE cur2 CURSOR SCROLL_LOCKS
FOR SELECT * FROM dbo.TableA;

DECLARE cur3 CURSOR OPTIMISTIC
FOR SELECT * FROM dbo.TableA;

DECLARE cur1 CURSOR TYPE_WARNING
FOR SELECT * FROM dbo.TableA;

DECLARE cur1 CURSOR
FOR SELECT * FROM dbo.TableA
FOR UPDATE;

DECLARE cur1 CURSOR
FOR SELECT * FROM dbo.TableA
FOR UPDATE OF col1, col2;

DECLARE cur1 CURSOR
FOR SELECT * FROM dbo.TableA
FOR READ_ONLY;

DECLARE @cur CURSOR
FOR SELECT * FROM dbo.TableA;

OPEN cur1;
CLOSE cur1;
DEALLOCATE cur1;

FETCH FROM cur1;
FETCH NEXT FROM cur1;
FETCH PRIOR FROM cur1;
FETCH FIRST FROM cur1;
FETCH LAST FROM cur1;

FETCH ABSOLUTE 5 FROM cur1;
FETCH RELATIVE 2 FROM cur1;

FETCH ABSOLUTE @n FROM cur1;
FETCH RELATIVE @n FROM cur1;

FETCH NEXT FROM cur1 INTO @a, @b, @c;
